### ISSUE TITLE
Add a RSS/Atom feed

### ISSUE THREAD

**Issue by timharek** [echo-webkom/echo-web-frontend#215]
On the current [echo.uib.no](https://echo.uib.no) I cannot find any RSS/Atom feed. It would be a very nice feature, as the old website had this.

**Comment by boaanes** [comment]
We will look into it!

**Comment by timharek** [comment]
https://echo.uib.no/rss.xml gives 404 😅

**Comment by boaanes** [comment]
> https://echo.uib.no/rss.xml gives 404

Yes. The the fix is not in production yet, but should be next tuesday :smile:
