### ISSUE TITLE
[Bug] RSS mangler nesten hele artikkelen og HTML formatering mangler

### ISSUE THREAD

**Issue by timharek** [echo-webkom/echo-web-frontend#314]
**Hvordan skjer buggen?**
Steg for å reprodusere:

1. Åpne RSS-feed i en RSS-leser
2. Åpne en artikkel/post

**Forventet oppførsel**
Enten en ingress av artikkelen eller hele artikkelen. Samtidig er det også ønskelig med ordentlig HTML-formatering og ikke Markdown som henger igjen 😅

<details>
<summary>Screenshots</summary>

<img width="507" alt="Skjermbilde 2021-05-14 kl  22 54 25" src="https://user-images.githubusercontent.com/5453010/118329709-56c3c080-b507-11eb-9cee-aee359aacee0.png">

</details>

**Detaljer:**

-   RSS-leser: NetNewsWire (både macOS og iOS), og Nextcloud News

**Eventuelle greier**
Jeg har lite erfaring med å lage RSS-feeds selv, men kanskje denne kan være til hjelp? https://validator.w3.org/feed/docs/rss2.html

**Comment by boaanes** [comment]
Ser ut som RSS-leseren din viser `description`, mulig du kan konfigruere den til å vise `content` i stedet dersom du vil se hele teksten? Har satt `description` til å vise de første 70 karakterene av artikkelen.

Markdown-formateringen skal fjernes, og HTML-formatering kan vi se litt nærmere på. Takk for feedback!

**Comment by timharek** [comment]
Ikke sant! Jeg har muligheten til å åpne Reader View i både Nextcloud News og NetNewsWire, det gjør det mulig å lese artiklene, så det løser faktisk problemet da 😅
