### ISSUE TITLE
[Bug] Datohåndtering for påmelding burde gjøres serverside og ikke klientside

### ISSUE THREAD

**Issue by sondr3** [echo-webkom/echo-web-frontend#510]
**Beskriv buggen**
Per nå kan man bare stille klokken på datamaskinen frem til etter påmeldingsfristen går ut og fylle ut skjemaet og sitte klar til slaget 12.00 f.eks., som gjør at alt man trenger å gjøre er å trykke send.

**Hvordan skjer buggen?**

1. Still klokken frem til etter påmeldingen.
2. Fyll ut skjemaet.
3. Vent til slaget 12.
4. ???
5. Profit

**Forventet oppførsel**
Skjemaet ikke kan fylles ut før etter påmeldingen begynner.

**Forslag**

Gjør sjekken for om påmeldingen skjer i `getServerSideProps`, og ha en ting klientside som automatisk refresher nettsiden når påmeldingen åpner slik at alle starter på samme fot.

**Comment by boaanes** [comment]
Tusen takk Sondre! Skal være fikset i #511. Test gjerne på bedprespåmeldingen på torsdag :smile:
